/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/model./model/cube.glb 
Author: Memorie (https://sketchfab.com/Memorie)
License: CC-BY-4.0 (http:/./model/creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-cube-2c4b8f6de26b4e869d342a92d881debe
Title: Sci-Fi Cube
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Cube(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('./model/cube.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} rotation={[0.1,1.6,0]} {...props} dispose={null} scale={3}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.002}>
          <group name="dd6ef14ae51b43909b1ee178a049bd4efbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Metal_Shell" position={[0, 0.277, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="0" geometry={nodes['0'].geometry} material={materials.Metal_Shell} morphTargetDictionary={nodes['0'].morphTargetDictionary} morphTargetInfluences={nodes['0'].morphTargetInfluences} />
                </group>
                <group name="Power_Cube" position={[0, 9.437, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={104.1}>
                  <mesh name="Power_Cube_Emission_0" geometry={nodes.Power_Cube_Emission_0.geometry} material={materials.Emission} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./model/cube.glb')
