/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/model./model/ai.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { useGSAP } from '@gsap/react'
import { useThree } from '@react-three/fiber'

import gsap from 'gsap'
import { ScrollTrigger } from 'gsap/all'
gsap.registerPlugin(ScrollTrigger)

export function Portal(props) {
  const { camera } = useThree()  // Access the camera from the scene

  const { nodes, materials } = useGLTF('./model/portal.glb')
    const ai = useRef()
    const text = useRef()
  materials.lampLight.color.set("red");
  materials.lampLight.roughness = 0.8;
  materials.lampLight.metalness = 0.5


// Initialize GSAP animations using useGSAP
useGSAP(() => {
  // const t1 = gsap.timeline();

  // // Scroll-triggered scaling for the Oculus model (Zoom-in effect)
  // t1.to(ai.current.scale, {
  //   x: 2,  // Scale on X-axis (zoom-in effect)
  //   y: 2,  // Scale on Y-axis
  //   z: 2,  // Scale on Z-axis
  //   duration: 2.5,
  //   scrollTrigger: {
  //     trigger: '.ai-container',
  //     start: '8% 8%',
  //     end: 'bottom bottom',
  //     scrub: 1,
  //   }
  // });

  // // Scroll-triggered position animation for the Oculus model
  // t1.to(ai.current.position, {
  //   y: 4.3,  // Center model vertically
  //   duration: 2.5,
  //   scrollTrigger: {
  //     trigger: '.ai-container',
  //     start: '8% 8%',
  //     end: 'bottom bottom',
  //     scrub: 1,
  //   }
  // });

  // // Scroll-triggered position animation for text (e.g., 3D text)
  // t1.to(text.current.position, {
  //   z: -25.3,  // Adjust Z-position of text
  //   scrollTrigger: {
  //     trigger: '.ai-container',
  //     start: '8% 8%',
  //     end: 'bottom bottom',
  //     scrub: 1,
  //   }
  // });

  // // Scroll-triggered camera zoom-in effect (move camera closer to model on the Z-axis)
  // t1.to(camera.position, {
  //   z: -8.5,  // Move camera closer on the Z-axis (zoom-in effect)
  //   y: 6,     // Move camera up on the Y-axis
  //   duration: 2.5,
  //   scrollTrigger: {
  //     trigger: '.ai-container',
  //     start: '8% 8%',
  //     end: 'bottom bottom',
  //     scrub: 1,
  //   }
  // });

  // // Fade-out effect for the `.ai-container` as it scrolls
  // t1.to(".ai-container", {
  //   opacity: 0,  // Fade out the `.ai-container`
  //   duration: 1.5,
  //   scrollTrigger: {
  //     trigger: '.ai-container',
  //     start: '80% 80%',  // Start fading when 80% of `.ai-container` hits the viewport
  //     end: 'bottom bottom', // End when `.ai-container` reaches the bottom of the viewport
  //     scrub: 2,  // Smoothly scrub the fade-out animation
  //   }
  // });

  // // Fade-in effect for the `.ai-container` when it enters the viewport
  // t1.to(".ai-container", {
  //   opacity: 1,  // Fade in the `.ai-container`
  //   duration: 1.5,
  //   scrollTrigger: {
  //     trigger: '.ai-container',
  //     start: 'top top',  // Start fading when the top of `.ai-container` hits the top of the viewport
  //     end: '5% 5%',  // End fading when 5% of `.ai-container` is scrolled
  //     scrub: 2,  // Smooth scrubbing of the fade-in animation
  //   }
  // });

});

  return (
    <group {...props} dispose={null} scale={1.7} ref={ai}>
      <mesh geometry={nodes.Cube001.geometry} material={materials.wood} position={[0.741, 0, 0.246]} rotation={[0, 0.117, 0]} scale={1.177} />
      <mesh geometry={nodes.Cube002.geometry} material={materials.wood} position={[0.777, 0, -0.864]} rotation={[0, -0.158, 0]} scale={1.177} />
      <mesh geometry={nodes.Cube003.geometry} material={materials.wood} position={[-0.729, 0, -0.746]} rotation={[Math.PI, -0.062, Math.PI]} scale={1.177} />
      <mesh geometry={nodes.Cube004.geometry} material={materials.wood} position={[-0.761, 0, 0.364]} rotation={[Math.PI, -0.081, Math.PI]} scale={1.177} />
      <mesh geometry={nodes.Cube005.geometry} material={materials.wood} position={[-0.714, 0, 1.474]} rotation={[-Math.PI, 0.038, -Math.PI]} scale={1.177} />
      <mesh geometry={nodes.Cube.geometry} material={materials.wood} position={[0.755, 0, 1.355]} scale={1.177} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials.wood} position={[1.212, 0.005, 0.904]} scale={1.149} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials.wood} position={[1.532, 0.005, 0.371]} scale={1.149} />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials.wood} position={[1.657, 0.005, 1.437]} scale={1.149} />
      <mesh geometry={nodes.Cylinder003.geometry} material={materials.wood} position={[1.106, 0.005, 1.721]} scale={1.149} />
      <mesh geometry={nodes.Cylinder004.geometry} material={materials.wood} position={[1.738, 0.004, 0.752]} rotation={[0, -0.505, Math.PI / 2]} scale={0.148} />
      <mesh geometry={nodes.Cylinder005.geometry} material={materials.wood} position={[1.049, 0.004, 1.155]} rotation={[0, 0, Math.PI / 2]} scale={0.148} />
      <mesh geometry={nodes.Cylinder006.geometry} material={materials.wood} position={[1.728, 0.004, 1.2]} rotation={[-Math.PI, -0.435, -Math.PI / 2]} scale={0.148} />
      <mesh geometry={nodes.Cylinder007.geometry} material={materials.wood} position={[1.808, 0.092, 0.734]} rotation={[-3.106, -1.094, -1.022]} scale={0.148} />
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.001']} position={[0, 0, 3.887]} scale={[0.788, 1.898, 6]} >
      </mesh>
      <mesh geometry={nodes.Cube008.geometry} material={materials.rock} position={[1.003, 0, 0.234]} />
      <mesh geometry={nodes.Cube012.geometry} material={materials.rock} position={[-0.949, 0, 0.234]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Cube009.geometry} material={materials.wood} position={[1.003, 0.458, 0.234]} scale={0.039} />
      <mesh geometry={nodes.Cube013.geometry} material={materials.wood} position={[-0.949, 0.458, 0.234]} rotation={[Math.PI, 0, Math.PI]} scale={0.039} />
      <mesh geometry={nodes.Cube010.geometry} material={materials.metal} position={[0.715, 1.066, 0.234]} scale={0.039} />
      <mesh geometry={nodes.Cube014.geometry} material={materials.metal} position={[-0.661, 1.066, 0.234]} rotation={[Math.PI, 0, Math.PI]} scale={0.039} />
      <mesh geometry={nodes.Cube011.geometry} material={materials.lampLight} position={[0.715, 1.066, 0.234]} scale={0.039} >
      <meshBasicMaterial args={[{ color: 'rgb(250, 100, 0)'}]} wireframe />

</mesh>
      <mesh geometry={nodes.Cube015.geometry} material={materials.lampLight} position={[-0.661, 1.066, 0.234]} rotation={[Math.PI, 0, Math.PI]} scale={0.039} >
      <meshBasicMaterial args={[{color:'red'}]}/>
      </mesh>
      <mesh geometry={nodes.Cube020.geometry} material={materials.rock} position={[1.43, 0, -1.507]} rotation={[0, 0.817, 0]} scale={[0.339, 0.585, 0.339]} />
      <mesh geometry={nodes.Cube021.geometry} material={materials.rock} position={[-1.576, 0, -1.583]} rotation={[Math.PI, -1.324, Math.PI]} scale={[0.364, 1.235, 0.364]} />
      <mesh geometry={nodes.Cube022.geometry} material={materials.rock} position={[-1.478, 0, -0.645]} rotation={[0, 1.137, 0]} scale={[0.254, 0.492, 0.329]} />
      <mesh geometry={nodes.Cube023.geometry} material={materials.rock} position={[-1.01, 0, -0.803]} rotation={[0, -0.712, 0]} scale={0.186} />
      <mesh geometry={nodes.Cube024.geometry} material={materials.rock} position={[1.638, 0, -0.793]} scale={0.251} />
      <mesh geometry={nodes.Cube025.geometry} material={materials.rock} position={[-0.941, 0, 0.572]} rotation={[-Math.PI, 1.018, -Math.PI]} scale={0.114} />
      <mesh geometry={nodes.Cube026.geometry} material={materials.rock} position={[-1.266, 0, 1.326]} rotation={[0, 0.27, 0]} scale={0.236} />
      <mesh geometry={nodes.Cube027.geometry} material={materials.rock} position={[-1.514, 0, 0.159]} rotation={[0, -0.162, 0]} scale={0.366} />
      <mesh geometry={nodes.Cube028.geometry} material={materials.rock} position={[1.198, 0, -0.424]} rotation={[0, 1.019, 0]} scale={0.107} />
      <mesh geometry={nodes.Cube029.geometry} material={materials.rock} position={[1.722, 0, -0.212]} rotation={[0, -0.693, 0]} scale={0.196} />
      <mesh geometry={nodes.Cube030.geometry} material={materials.rock} position={[-1.644, 0, 0.836]} rotation={[0, 0.293, 0]} scale={0.196} />
      <mesh geometry={nodes.Cube031.geometry} material={materials.rock} position={[-1.011, 0, -1.361]} rotation={[-Math.PI, 0.745, -Math.PI]} scale={[0.186, 0.39, 0.186]} />
      <mesh geometry={nodes.Cube032.geometry} material={materials.rock} position={[1.099, 0, -0.903]} rotation={[0, 1.22, 0]} scale={[0.236, 0.333, 0.236]} />
      <mesh geometry={nodes.Cube033.geometry} material={materials.rock} position={[1.167, 0, 0.542]} rotation={[0, 0.817, 0]} scale={[0.072, 0.124, 0.072]} />
      <mesh geometry={nodes.Cube034.geometry} material={materials.rock} position={[1.374, 0, 1.242]} rotation={[-Math.PI, 0.745, -Math.PI]} scale={[0.088, 0.184, 0.088]} />
      <mesh geometry={nodes.Cube035.geometry} material={materials.rock} position={[0.857, 0, 0.861]} rotation={[0, -0.285, 0]} scale={0.084} />
      <mesh geometry={nodes.Cube036.geometry} material={materials.rock} position={[-1.786, 0, -1.033]} rotation={[0, 0.503, 0]} scale={0.147} />
      <mesh geometry={nodes.Cube017.geometry} material={materials.rock} position={[0, 0.854, -1.769]} rotation={[0, 0, 0.864]} scale={0.785} />
      <mesh geometry={nodes.Cube018.geometry} material={materials.rock} position={[0, 0.854, -1.769]} rotation={[0, 0, 1.369]} scale={0.785} />
      <mesh geometry={nodes.Cube019.geometry} material={materials.rock} position={[0, 0.854, -1.769]} rotation={[0, 0, 1.875]} scale={0.785} />
      <mesh geometry={nodes.Cube037.geometry} material={materials.rock} position={[0, 0.854, -1.769]} rotation={[0, 0, 2.38]} scale={0.785} />
      <mesh geometry={nodes.Cube038.geometry} material={materials.rock} position={[0, 0.854, -1.769]} rotation={[0, 0, 2.886]} scale={0.785} />
      <mesh geometry={nodes.Cube039.geometry} material={materials.rock} position={[0, 0.854, -1.769]} rotation={[0, 0, -2.892]} scale={0.785} />
      <mesh geometry={nodes.Cube040.geometry} material={materials.rock} position={[0, 0.854, -1.769]} rotation={[0, 0, -2.386]} scale={0.785} />
      <mesh geometry={nodes.Cube041.geometry} material={materials.rock} position={[0, 0.854, -1.769]} rotation={[0, 0, -1.88]} scale={0.785} />
      <mesh geometry={nodes.Cube042.geometry} material={materials.rock} position={[0, 0.854, -1.769]} rotation={[0, 0, -1.375]} scale={0.785} />
      <mesh geometry={nodes.Cube043.geometry} material={materials.rock} position={[0, 0.854, -1.769]} rotation={[0, 0, -0.869]} scale={0.785} />
      <mesh geometry={nodes.Cube016.geometry} material={materials.rock} position={[0, 0.145, -1.769]} scale={[1.307, 0.212, 0.345]} />
      <mesh geometry={nodes.Cube044.geometry} material={materials.rock} position={[0, 0.074, -1.442]} scale={[1.019, 0.165, 0.269]} />
      <mesh geometry={nodes.Cube045.geometry} material={materials.rock} position={[0, 0, -1.182]} scale={[0.815, 0.132, 0.215]} />
      <mesh color="grey"   metalness={0.8}
                roughness={0.7} geometry={nodes.Circle.geometry} material={materials.portalLight} position={[0, 0.851, -1.774]} rotation={[Math.PI / 2, 0, 0]} scale={0.721} />
      <mesh geometry={nodes.Plane001.geometry} material={materials.grass} position={[1.575, 0, 3.887]} scale={[0.788, 1.898, 6]} />
      <mesh geometry={nodes.Plane002.geometry} material={materials.grass} position={[-1.563, 0, 3.887]} scale={[0.788, 1.898, 6]} />
      <mesh geometry={nodes.Cube046.geometry} material={materials.wood} position={[0.678, -0.048, 3.55]} rotation={[0, 0.117, 0]} scale={1.177} />
      <mesh geometry={nodes.Cube047.geometry} material={materials.wood} position={[0.678, -0.048, 2.441]} rotation={[0, -0.158, 0]} scale={1.177} />
      <mesh geometry={nodes.Cube048.geometry} material={materials.wood} position={[-0.792, -0.048, 2.559]} rotation={[Math.PI, -0.062, Math.PI]} scale={1.177} />
      <mesh geometry={nodes.Cube049.geometry} material={materials.wood} position={[-0.777, -0.048, 3.669]} rotation={[Math.PI, -0.081, Math.PI]} scale={1.177} />
      <mesh geometry={nodes.Cube050.geometry} material={materials.wood} position={[-0.777, -0.048, 4.779]} rotation={[-Math.PI, 0.038, -Math.PI]} scale={1.177} />
      <mesh geometry={nodes.Cube051.geometry} material={materials.wood} position={[0.693, -0.048, 4.66]} scale={1.177} />
      <mesh geometry={nodes.Cube052.geometry} material={materials.rock} position={[0.94, -0.048, 3.539]} />
      <mesh geometry={nodes.Cube053.geometry} material={materials.wood} position={[0.94, 0.41, 3.539]} scale={0.039} />
      <mesh geometry={nodes.Cube055.geometry} material={materials.wood} position={[-1.012, 0.41, 3.539]} rotation={[Math.PI, 0, Math.PI]} scale={0.039} />
      <mesh geometry={nodes.Cube054.geometry} material={materials.metal} position={[0.652, 1.018, 3.539]} scale={0.039} />
      <mesh geometry={nodes.Cube056.geometry} material={materials.metal} position={[-0.724, 1.018, 3.539]} rotation={[Math.PI, 0, Math.PI]} scale={0.039} />
      <mesh geometry={nodes.Cube057.geometry} material={materials.rock} position={[-1.014, -0.016, 3.542]} />
      <mesh geometry={nodes.Cube058.geometry} material={materials.lampLight} position={[-0.724, 1.017, 3.538]} rotation={[Math.PI, 0, Math.PI]} scale={0.039} />
      <mesh geometry={nodes.Cube059.geometry} material={materials.lampLight} position={[0.651, 1.016, 3.538]} rotation={[Math.PI, 0, Math.PI]} scale={0.039} />
      <mesh geometry={nodes.Cylinder008.geometry} material={materials.wood} position={[-1.744, 0.022, 4.143]} scale={1.149} />
      <mesh geometry={nodes.Cylinder009.geometry} material={materials.wood} position={[-1.425, 0.022, 3.61]} scale={1.149} />
      <mesh geometry={nodes.Cylinder010.geometry} material={materials.wood} position={[-1.3, 0.022, 4.676]} scale={1.149} />
      <mesh geometry={nodes.Cylinder011.geometry} material={materials.wood} position={[-1.851, 0.022, 4.96]} scale={1.149} />
      <mesh geometry={nodes.Cylinder012.geometry} material={materials.wood} position={[-1.219, 0.02, 3.991]} rotation={[0, -0.505, Math.PI / 2]} scale={0.148} />
      <mesh geometry={nodes.Cylinder013.geometry} material={materials.wood} position={[-1.908, 0.02, 4.394]} rotation={[0, 0, Math.PI / 2]} scale={0.148} />
      <mesh geometry={nodes.Cylinder014.geometry} material={materials.wood} position={[-1.229, 0.02, 4.439]} rotation={[-Math.PI, -0.435, -Math.PI / 2]} scale={0.148} />
      <mesh geometry={nodes.Cylinder015.geometry} material={materials.wood} position={[-1.148, 0.109, 3.973]} rotation={[-3.106, -1.094, -1.022]} scale={0.148} />
      <mesh geometry={nodes.Cube060.geometry} material={materials.metal} position={[-1.721, 0.306, 4.134]} rotation={[0, 0, 0.177]} scale={0.096} />
      <mesh geometry={nodes.Cube061.geometry} material={materials.wood} position={[-1.728, 0.359, 4.134]} rotation={[-3.14, 0.019, 3.142]} scale={0.096} />
      <mesh geometry={nodes.Cube062.geometry} material={materials.rock} position={[-1.319, 0.017, 2.446]} scale={0.251} />
      <mesh geometry={nodes.Cube063.geometry} material={materials.rock} position={[-1.759, 0.017, 2.814]} rotation={[0, 1.019, 0]} scale={0.107} />
      <mesh geometry={nodes.Cube064.geometry} material={materials.rock} position={[-1.235, 0.017, 3.027]} rotation={[0, -0.693, 0]} scale={0.196} />
      <mesh geometry={nodes.Cube065.geometry} material={materials.rock} position={[-1.858, 0.017, 2.336]} rotation={[0, 1.22, 0]} scale={[0.236, 0.333, 0.236]} />
      <mesh geometry={nodes.Cube066.geometry} material={materials.rock} position={[-1.79, 0.017, 3.781]} rotation={[0, 0.817, 0]} scale={[0.072, 0.124, 0.072]} />
      <mesh geometry={nodes.Cube067.geometry} material={materials.rock} position={[-1.583, 0.017, 4.481]} rotation={[-Math.PI, 0.745, -Math.PI]} scale={[0.088, 0.184, 0.088]} />
      <mesh geometry={nodes.Cube068.geometry} material={materials.rock} position={[-2.1, 0.017, 4.099]} rotation={[0, -0.285, 0]} scale={0.084} />
      <mesh geometry={nodes.Cube069.geometry} material={materials.rock} position={[1.46, -0.002, 3.342]} rotation={[0, 1.137, 0]} scale={[0.254, 0.492, 0.329]} />
      <mesh geometry={nodes.Cube070.geometry} material={materials.rock} position={[1.928, -0.002, 3.183]} rotation={[0, -0.712, 0]} scale={0.186} />
      <mesh geometry={nodes.Cube071.geometry} material={materials.rock} position={[1.997, -0.002, 4.559]} rotation={[-Math.PI, 1.018, -Math.PI]} scale={0.114} />
      <mesh geometry={nodes.Cube072.geometry} material={materials.rock} position={[1.672, -0.002, 5.313]} rotation={[0, 0.27, 0]} scale={0.236} />
      <mesh geometry={nodes.Cube073.geometry} material={materials.rock} position={[1.424, -0.002, 4.146]} rotation={[0, -0.162, 0]} scale={0.366} />
      <mesh geometry={nodes.Cube074.geometry} material={materials.rock} position={[1.294, -0.002, 4.822]} rotation={[0, 0.293, 0]} scale={0.196} />
      <mesh geometry={nodes.Cube075.geometry} material={materials.rock} position={[1.927, -0.002, 2.626]} rotation={[-Math.PI, 0.745, -Math.PI]} scale={[0.186, 0.39, 0.186]} />
      <mesh geometry={nodes.Cube076.geometry} material={materials.rock} position={[1.152, -0.002, 2.953]} rotation={[0, 0.503, 0]} scale={0.147} />
      <group ref={text}>
      <mesh geometry={nodes.Text.geometry} material={materials['Material.002']} position={[-0.001, 0.001, 5.051]} scale={2} />
      </group>
    </group>
  )
}

useGLTF.preload('./model/portal.glb')
