/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/model./model/space3.glb 
Author: AiSpica (https://sketchfab.com/AiSpica)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/artificial-intelligence-aispica-57761aa23b7746489c85371334fa7a95
Title: Artificial Intelligence AiSpica
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Space(props) {
  const { nodes, materials } = useGLTF('./model/space3.glb')
  return (
    <group {...props} dispose={null} rotation={[0,2,0]}>
      <mesh geometry={nodes.Object_10.geometry} material={materials.Materiale} position={[0, 0.28, 0]} rotation={[1.571, 0.087, 1.567]} scale={2.216} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.Risorsa_1193} position={[0.223, -0.114, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.015} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.Risorsa_1203} position={[1.3, 0.102, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.015} />
      <mesh geometry={nodes.Object_32.geometry} material={materials.Risorsa_1253} position={[0.992, 0.04, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.015} />
      <mesh geometry={nodes.Object_38.geometry} material={materials.Risorsa_1283} position={[0.916, 0.025, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.015} />
      <mesh geometry={nodes.Object_46.geometry} material={materials.Risorsa_1323} position={[0.685, -0.021, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.015} />
      <mesh geometry={nodes.Object_52.geometry} material={materials.Risorsa_1353} position={[0.454, -0.068, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.015} />
      <mesh geometry={nodes.Object_56.geometry} material={materials.Risorsa_1373} position={[0.3, -0.098, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.015} />
      <mesh geometry={nodes.Object_58.geometry} material={materials.Risorsa_1383} position={[1.069, 0.056, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.015} />
      <mesh geometry={nodes.Object_60.geometry} material={materials.Risorsa_1393} position={[1.377, 0.117, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.015} />
      <mesh geometry={nodes.Object_64.geometry} material={materials.Risorsa_1413} position={[0.069, -0.145, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.015} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.Risorsa_1213} position={[-0.393, -0.237, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.015} />
      <mesh geometry={nodes.Object_26.geometry} material={materials.Risorsa_1223} position={[1.146, 0.071, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.015} />
      <mesh geometry={nodes.Object_28.geometry} material={materials.Risorsa_1233} position={[-0.316, -0.221, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.015} />
      <mesh geometry={nodes.Object_30.geometry} material={materials.Risorsa_1243} position={[-0.239, -0.206, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.015} />
      <mesh geometry={nodes.Object_34.geometry} material={materials.Risorsa_1263} position={[-0.162, -0.191, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.015} />
      <mesh geometry={nodes.Object_36.geometry} material={materials.Risorsa_1273} position={[-0.085, -0.175, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.015} />
      <mesh geometry={nodes.Object_40.geometry} material={materials.Risorsa_1293} position={[0.839, 0.009, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.015} />
      <mesh geometry={nodes.Object_42.geometry} material={materials.Risorsa_1303} position={[0.762, -0.006, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.015} />
      <mesh geometry={nodes.Object_44.geometry} material={materials.Risorsa_1313} position={[0.608, -0.037, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.015} />
      <mesh geometry={nodes.Object_48.geometry} material={materials.Risorsa_1333} position={[0.531, -0.052, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.015} />
      <mesh geometry={nodes.Object_50.geometry} material={materials.Risorsa_1343} position={[1.223, 0.086, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.015} />
      <mesh geometry={nodes.Object_54.geometry} material={materials.Risorsa_1363} position={[0.377, -0.083, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.015} />
      <mesh geometry={nodes.Object_62.geometry} material={materials.Risorsa_1403} position={[0.146, -0.129, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.015} />
      <mesh geometry={nodes.Object_66.geometry} material={materials.Risorsa_1423} position={[-0.008, -0.16, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.015} />
      <mesh geometry={nodes.Object_68.geometry} material={materials.Ceramic_Polished} position={[0.242, -0.002, 0.091]} rotation={[1.568, 0.087, -1.57]} scale={[0.016, 0.016, 0.017]} />
      <instancedMesh args={[nodes.Object_0.geometry, materials.material_0, 7]} instanceMatrix={nodes.Object_0.instanceMatrix} />
    </group>
  )
}

useGLTF.preload('./model/space3.glb')
